export {execLocal} from './exec-local'
export {renderFrame} from '../../current-user/exec-service/strategies/utils/web/render/render-frame'
export {renderPop} from '../../current-user/exec-service/strategies/utils/web/render/render-pop'
export {renderTab} from '../../current-user/exec-service/strategies/utils/web/render/render-tab'
export {getDefaultConfig} from './default-config'
