name: Requesting a Feature or Improvement
description: For feature requests. Please search for existing issues first. Also see CONTRIBUTING.
title: "[FEATURE] <title>"
labels: [Feature, Needs Triage]
body:
  - type: markdown
    attributes:
      value: Please fill out the template below to the best of your ability and include a label indicating which tool/service you were working with when you encountered the problem.
  - type: textarea
    attributes:
      label: Issue to be solved
      description: Please present a concise description of the problem to be addressed by this feature request. Please be clear what parts of the problem are considered to be in-scope and out-of-scope.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Suggest A Solution
      description: |
        A concise description of your preferred solution. Things to address include:
          * Details of the technical implementation
          * Tradeoffs made in design decisions
          * Caveats and considerations for the future

        If there are multiple solutions, please present each one separately. Save comparisons for the very end.)
    validations:
      required: false
  - type: textarea
    attributes:
      label: What are you currently working on that this is blocking?
    validations:
      required: false
