name: Generate and Publish Documentation

on:
  release:
    types: [published]
    branches:
      - master

jobs:
  generate-and-publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fcl-js repo
        uses: actions/checkout@v3
        with:
          path: fcl-js

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: fcl-js/package-lock.json

      - name: Install dependencies
        run: |
          cd fcl-js
          npm ci

      - name: Generate documentation
        run: |
          cd fcl-js
          npm run generate-all-docs
          echo "FCL_JS_COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Checkout onflow/docs repo
        uses: actions/checkout@v3
        with:
          repository: onflow/docs
          path: flow-docs
          token: ${{ secrets.DOCS_REPO_TOKEN }}

      - name: Create branch in docs repo
        run: |
          cd flow-docs
          git config user.name "FCL Docs Generator"
          git config user.email "fcl-docs-generator@users.noreply.github.com"
          git checkout -b "docs-generator/fcl-js-${{ env.FCL_JS_COMMIT }}"

      - name: Copy documentation to docs repo
        run: |
          # Define the source and destination directories
          SRC_DIR="fcl-js/docs-generator/output/fcl-docs"
          DEST_DIR="flow-docs/docs/fcl-js"

          # Create destination directory if it doesn't exist
          mkdir -p "$DEST_DIR"

          # Copy all generated docs to the docs repo
          cp -r "$SRC_DIR"/* "$DEST_DIR"/

      - name: Commit and push changes to docs repo
        run: |
          cd flow-docs
          git add .
          git commit -m "Update FCL JS documentation from fcl-js@${{ env.FCL_JS_COMMIT }}"
          git push --set-upstream origin "docs-generator/fcl-js-${{ env.FCL_JS_COMMIT }}"

      - name: Create Pull Request in docs repo
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.DOCS_REPO_TOKEN }}
          path: flow-docs
          commit-message: "Update FCL JS documentation from fcl-js@${{ env.FCL_JS_COMMIT }}"
          branch: "docs-generator/fcl-js-${{ env.FCL_JS_COMMIT }}"
          base: main
          title: "Update FCL JS documentation from fcl-js@${{ env.FCL_JS_COMMIT }}"
          body: |
            This PR updates the FCL JS documentation from the latest changes in the [fcl-js repo](https://github.com/onflow/fcl-js/commit/${{ env.FCL_JS_COMMIT }}).

            Documentation was automatically generated by the docs-generator workflow.
          draft: false
